global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'user_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8000']

  - job_name: 'party_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['party-service:8100']

  - job_name: 'member_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['member-service:8200']

  - job_name: 'bill_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bill-service:8300']

  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'notification-service:8400' ]
