package com.menstalk.userservice.user.controller;

import com.menstalk.userservice.user.dto.UserResponse;
import com.menstalk.userservice.user.service.UserService;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/user")
@RequiredArgsConstructor
@Api(tags = "User Api")
public class UserController {
    private final UserService userService;

    @GetMapping("/info")
    @ApiOperation("(External) Show user info by id from header 'userId' which generated by token")
    public ResponseEntity<UserResponse> getByUserId(@RequestHeader(name = "id") String userId) {
        return new ResponseEntity<>(userService.getByUserId(Long.valueOf(userId)), HttpStatus.OK);
    }
    
    @GetMapping("/{userId}")
    @ApiOperation("(Internal) Find user by userId for feign")
    public ResponseEntity<UserResponse> findUserByUserId(@PathVariable("userId") Long userId) {
        return new ResponseEntity<>(userService.getByUserId(userId), HttpStatus.OK);
    }

    @GetMapping("/search/{username}")
    @ApiOperation("(Internal) Find user by username for search")
    public ResponseEntity<UserResponse> findUserByUsername(@PathVariable("username") String username) {
        UserResponse userResponse = userService.getByUsername(username);
        if (userResponse != null) {
            return new ResponseEntity<>(userService.getByUsername(username), HttpStatus.OK);
        } else {
            return new ResponseEntity<>(null, HttpStatus.OK);
        }
    }

    @GetMapping("/admin/findAll")
    @ApiOperation("(Admin) FindAllUsers")
    public ResponseEntity<List<UserResponse>> findAll(@RequestHeader(value = "role", required = false) String role) {
        try {
            if (role.equals("admin")) {
                return new ResponseEntity<>(userService.getAllUsers(), HttpStatus.OK);
            } else {
                return new ResponseEntity<>(null, HttpStatus.BAD_REQUEST);
            }
        } catch (Exception e) {
            return new ResponseEntity<>(null, HttpStatus.BAD_REQUEST);
        }
    }

}
